server:
  port: ${APP_PORT:8081}

spring:
  application:
    name: ${APP_NAME:unnamed}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      max-poll-records: 100
      max-partition-fetch-bytes: 1000000
    topic:
      topic-name:registration_topic
      src-field:email
  datasource:
    url: jdbc:mysql://localhost:3306/myschemas?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dirver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

pebble:
  suffix:
  cache: false
